apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort  # You can also use LoadBalancer or ClusterIP depending on access needs
  selector:
    app: api-gateway
  ports:
    - port: 8080           # The port that the service will expose
      targetPort: 8080      # The container's port that is being forwarded
      nodePort: 30001       # Exposed port on the Minikube VM
