server:
  port: 8071
  api:
    base-path: /api/user

logging:
  level:
    root: INFO
    com.riseroots: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-management.log

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SharathDharmala/RiseRootsRepository.git
          default-label: master  # Branch name
          search-paths: config  # Folder inside repo
  mvc:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  application:
    name: user-management-service

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  devtools:
    restart:
      enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sharath0205.eu.auth0.com/

user:
  initial-username: admin
  initial-password: admin123
  
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "env"
cors:
  allowed-origin: http://localhost:3000

api:
  user:
    login: "/api/user/login"
    
security:
  password-pattern: "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{6,}$"
    
messages:
  invalidCreds: "Invalid credentials: "
  loginSuccess: "Login is Successful.."
  usernameRequired: "Username is required"
  passwordRequired: "Password is required"

  
jwt:
  secret: "W4L2tXnoueFvWg40rx0gAmXIINtGDIvRxSAkJB3qLtM="
  expiration: 3600000