apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cronservice
spec:
  selector:
    app: cronservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.cronservice.service.port }}
  type: ClusterIP
