server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SharathDharmala/RiseRootsRepository.git
          default-label: master
          clone-on-start: true
  application:
    name: riseroots-spring-cloud-config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: refresh
