spring:
  application:
    name: kafka-consumer-service-2
  kafka:
    consumer:
      group-id: consumer-group-2
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081  # Schema Registry URL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8092

logging:
  level:
    root: INFO
    com.riseroots: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/kafkaconsumerservice-2.log