spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riseroots
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 30000
      connection-timeout: 30000
      pool-name: HikariCP
      leak-detection-threshold: 2000
      maximum-pool-size: 5
      minimum-idle: 1
      auto-commit: false